# Generated by Django 4.2.1 on 2023-05-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productbrand',
            options={'verbose_name_plural': 'ProductsBrand'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'ProductsCategories'},
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productbrand',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table=None,
        ),
    ]
