# Generated by Django 4.2.1 on 2023-05-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options_alter_productbrand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcategory'),
        ),
    ]
