# Generated by Django 4.2.1 on 2023-05-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='category',
            new_name='Parent',
        ),
    ]
