# Generated by Django 4.2.1 on 2023-05-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Discounted',
            field=models.BooleanField(default=False),
        ),
    ]
