# Generated by Django 4.2.1 on 2023-05-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidersetting',
            name='short_description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='slidersetting',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
