# Generated by Django 4.2.1 on 2023-05-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0002_slidersetting_short_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('banner', models.ImageField(upload_to='', verbose_name='advertise/')),
                ('url_title', models.URLField()),
                ('position', models.CharField(choices=[('index-page', 'Home'), ('product-list-page', 'Product List')], max_length=200)),
            ],
        ),
    ]
