# Generated by Django 4.2.1 on 2023-05-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0003_advertising'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='banner',
            field=models.ImageField(upload_to='advertise/'),
        ),
    ]
