# Generated by Django 4.2.1 on 2023-06-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_alter_discountcode_category_alter_discountcode_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='user',
        ),
    ]
