# Generated by Django 4.2.1 on 2023-05-22 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url_title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'ArticleCategories',
            },
        ),
        migrations.CreateModel(
            name='ArticleTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url_title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'ArticleTags',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('banner', models.ImageField(upload_to='articles/')),
                ('date', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField()),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articlecategories')),
                ('tags', models.ManyToManyField(to='article.articletags')),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
