# Generated by Django 4.2.1 on 2023-05-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_articlecomment_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, unique=True),
        ),
    ]
