# Generated by Django 4.2.1 on 2023-05-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contactus_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'ContactUs'},
        ),
        migrations.AlterModelTable(
            name='contactus',
            table=None,
        ),
    ]
