# Generated by Django 4.2.1 on 2023-06-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='price',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='final_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
